### ISSUE TITLE
Import only the react-intl and intl data that are necessary

### ISSUE THREAD

**Issue by klzns** [vtex-apps/render-runtime#10]
Today we have hard coded:
https://github.com/vtex-apps/render-runtime/blob/master/react/index.js

```js
import Intl from 'intl'
import pt from 'react-intl/locale-data/pt'
import en from 'react-intl/locale-data/en'
import es from 'react-intl/locale-data/es'
import 'intl/locale-data/jsonp/pt.js'
import 'intl/locale-data/jsonp/en.js'
import 'intl/locale-data/jsonp/es.js'
```
We need to add `fr`, `ca` and `ro` to that list adding more kbs to all clients and that doesn't scale. We should change that to be loaded async using dynamic import.

When we used Webpack we used to use this component to ease this process:
https://github.com/vtex/intl-container

On thing to consider is how [react-loadable](https://github.com/thejameskyle/react-loadable) does to server side render async modules.

**Comment by firstdoit** [comment]
@brunoabreu I think this is done, right?

**Comment by firstdoit** [comment]
Done!
