### ISSUE TITLE
Use host instead of hostname

### ISSUE THREAD

**Issue by ericoloewe** [vtex-apps/render-runtime#338]
Running vtex at local environment `https://<accountName>.vtexlocal.com.br:<port>` we can't access `/_secure/account#/profile`

It happens when you are using the local vtex server

To reproduce just follow the steps:

1.  Start your vtex-local server (proxy)
2.  Go to `https://<accountName>.vtexlocal.com.br:<port>/_secure/account#/profile`
3.  Try to edit your account and you will receive the message below

![image](https://user-images.githubusercontent.com/8793862/60513046-8ddeaf00-9cac-11e9-99dd-624c34734766.png)

The [`getBaseURI`](https://github.com/vtex-apps/render-runtime/blob/master/react/utils/host.ts#L15) must use **host** not **hostname**

Any device

**Comment by klzns** [comment]
Can you give the steps on how to reproduce?

**Comment by ericoloewe** [comment]
> Can you give the steps on how to reproduce?

Better now?

**Comment by klzns** [comment]
Which application is `vtex-local`?

What you talking about https://github.com/vtex/speed?

**Comment by ericoloewe** [comment]
> Which application is `vtex-local`?
> 
> Are you talking about https://github.com/vtex/speed?

Yes

**Comment by klzns** [comment]
VTEX Speed doesn't work if you're building stores using VTEX IO.

**Comment by ericoloewe** [comment]
Yes, I know about it, and I am not building a store using VTEX IO.
But, our store are using the new VTEX my account and that are using VTEX IO...

It is simple to fix this issue, if you could fix it, you will help our team to develop vtex stores 😄

**Comment by ericoloewe** [comment]
@klzns any updates about the issue?
